server:
  port: 8888
spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/prachichandrikapure/SupplyChainManagementSystem
          clone-on-start: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/